#!/usr/bin/env bash
# Shared CRE deployment-runbook helpers (sourced). Command syntax verified against the installed CLI (v1.33.0):
#   cre workflow build|deploy|activate|pause|get --help, cre secrets create --help, cre execution list|status|events|logs --help
# Never prints, reads or echoes secret values.
set -euo pipefail

CRE_BIN="${CRE_BIN:-${HOME}/.cre/bin/cre}"
[[ -x "$CRE_BIN" ]] || { echo "BLOCKED: CRE CLI not found at $CRE_BIN (https://docs.chain.link/cre)" >&2; exit 2; }
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PROJECT_ROOT="$REPO_ROOT/workflows"                  # project.yaml + secrets.yaml
WORKFLOW="identity-confidential"                     # folder under the project root
CRE_TARGET="${CRE_TARGET:-production-settings}"      # workflow.yaml target: deployment-registry "private"
WORKFLOW_NAME="identity-confidential-production"     # user-workflow.workflow-name of that target
DEPLOY_CONFIG=".deploy/config.json"                  # generated by configure.sh (relative to the workflow folder)

# The private (Chainlink-hosted) registry only — never the on-chain registry without explicit maintainer approval.
refuse_onchain() {
  if awk "/^${CRE_TARGET}:/{f=1;next} /^[a-z]/{f=0} f" "$PROJECT_ROOT/$WORKFLOW/workflow.yaml" | grep -q 'onchain:'; then
    echo "REFUSED: target $CRE_TARGET uses an on-chain registry" >&2
    exit 2
  fi
}

cre_header() {
  local step="$1" mode="$2" changes="$3" expected="$4"
  printf '\n%s\n[Chainlink CRE — %s]\n%s\n' "────────────────────────────────────────" "$step" "────────────────────────────────────────"
  printf 'Actor:    Maintainer (cre login required for live steps)\nMode:     %s\nChanges:  %s\nExpected: %s\nTarget:   %s (%s)\n\n' \
    "$mode" "$changes" "$expected" "$CRE_TARGET" "$WORKFLOW_NAME"
}

is_live() { for a in "$@"; do [[ "$a" == "--live" ]] && return 0; done; return 1; }
cre() { (cd "$PROJECT_ROOT" && "$CRE_BIN" "$@"); }
