import { verifyProof, type DataIntegrityProof } from '@catenor-one/credentials';
import {
  authorizesAssertion,
  decodeEd25519Multikey,
  findVerificationMethod,
  type DidDocument,
  type KeyManagementReference,
} from '@catenor-one/identity';
import type { FactInput } from '@catenor-one/policy';

export const ADMIT_TRUST_ANCHOR = 'ADMIT_TRUST_ANCHOR';
/** TTL of a key-possession challenge (PLAN §14.1). */
export const CHALLENGE_TTL_SECONDS = 300;

/** The signed challenge document [REF-IMPL; protocol replay rules are Open C] (PLAN §14.1). */
export interface KeyPossessionChallenge {
  readonly type: 'CatenorOneKeyPossessionChallenge';
  readonly challengeId: string;
  readonly subject: string;
  readonly verificationMethod: string;
  readonly operation: typeof ADMIT_TRUST_ANCHOR;
  readonly trustDomain: string;
  readonly nonce: string;
  readonly issuedAt: string;
  readonly expiresAt: string;
}

export type ChallengeStatus = 'ISSUED' | 'CONSUMED';

/** Server-side challenge record: the signed document plus its single-use status. */
export interface ChallengeRecord {
  readonly challenge: KeyPossessionChallenge;
  readonly status: ChallengeStatus;
}

export function issueChallenge(input: {
  challengeId: string;
  subject: string;
  verificationMethod: string;
  trustDomain: string;
  /** base64url of 32 CSPRNG bytes, generated by the caller. */
  nonce: string;
  issuedAt: Date;
}): ChallengeRecord {
  if (!/^[A-Za-z0-9_-]{43}$/.test(input.nonce)) {
    throw new TypeError('nonce must be base64url of 32 random bytes');
  }
  const expiresAt = new Date(input.issuedAt.getTime() + CHALLENGE_TTL_SECONDS * 1000);
  return {
    status: 'ISSUED',
    challenge: {
      type: 'CatenorOneKeyPossessionChallenge',
      challengeId: input.challengeId,
      subject: input.subject,
      verificationMethod: input.verificationMethod,
      operation: ADMIT_TRUST_ANCHOR,
      trustDomain: input.trustDomain,
      nonce: input.nonce,
      issuedAt: toRfc3339(input.issuedAt),
      expiresAt: toRfc3339(expiresAt),
    },
  };
}

/** Single-use consumption (PLAN §14.3 step 9 is enforced atomically by the repository). */
export function consumeChallenge(record: ChallengeRecord): ChallengeRecord {
  if (record.status !== 'ISSUED') throw new Error('CHALLENGE_CONSUMED');
  return { ...record, status: 'CONSUMED' };
}

export type KeyPossessionReason =
  | 'CHALLENGE_UNKNOWN'
  | 'CHALLENGE_CONSUMED'
  | 'CHALLENGE_EXPIRED'
  | 'CHALLENGE_SUBJECT_MISMATCH'
  | 'CHALLENGE_CONTEXT_MISMATCH'
  | 'VERIFICATION_METHOD_MISSING'
  | 'VERIFICATION_METHOD_NOT_FOR_ASSERTION'
  | 'KEY_PURPOSE_NOT_CREDENTIAL_ASSERTION'
  | 'PROOF_BINDING_MISMATCH'
  | 'SIGNATURE_INVALID';

export interface KeyPossessionResult {
  readonly possessionValid: boolean;
  /** `undefined` when verification stopped before key purpose was evaluated (step 6 not reached). */
  readonly purposeValid: boolean | undefined;
  readonly reasons: readonly KeyPossessionReason[];
  /**
   * `ASSERTION_KEY_POSSESSION_VALID`, plus `ASSERTION_KEY_PURPOSE_VALID` only when purpose was evaluated —
   * an unevaluated purpose is absent, so the policy trace records it as MISSING, never FALSE.
   */
  readonly facts: readonly FactInput[];
}

export interface VerifyKeyPossessionInput {
  /** `undefined` when no challenge exists for the presented id. */
  readonly record: ChallengeRecord | undefined;
  readonly requestedSubject: string;
  readonly trustDomain: string;
  /** Resolved public DID state of the requested subject. */
  readonly didDocument: DidDocument;
  /** Key-management reference of the verification method named by the proof, if any. */
  readonly keyReference: KeyManagementReference | undefined;
  readonly proof: DataIntegrityProof;
  readonly now: Date;
}

/**
 * `KeyPossessionVerifier` (PLAN §14.3 steps 1–8): uses only public DID state and the server challenge
 * record; it never throws for untrusted input. A failure yields `ASSERTION_KEY_POSSESSION_VALID = false`
 * with a reason. `ASSERTION_KEY_PURPOSE_VALID` is `false` only when purpose was evaluated (step 6) and found
 * invalid; when verification stops earlier it is not produced (MISSING) — maintainer decision 2026-09-11.
 *
 * Infrastructure failures (challenge store or DID resolution unavailable) are application errors: callers
 * must not invoke this verifier without a loaded challenge lookup and resolved DID Document, and no fact is
 * produced for them.
 */
export function verifyKeyPossession(input: VerifyKeyPossessionInput): KeyPossessionResult {
  const reasons: KeyPossessionReason[] = [];
  const done = (
    possessionValid: boolean,
    purposeValid: boolean | undefined,
  ): KeyPossessionResult => {
    const ref = input.record?.challenge.challengeId ?? 'challenge:unknown';
    return {
      possessionValid,
      purposeValid,
      reasons,
      facts: [
        fact('ASSERTION_KEY_POSSESSION_VALID', possessionValid, ref),
        ...(purposeValid === undefined
          ? []
          : [fact('ASSERTION_KEY_PURPOSE_VALID', purposeValid, ref)]),
      ],
    };
  };
  /** Verification stopped before step 6: possession is false, purpose was not evaluated. */
  const stop = (reason: KeyPossessionReason) => (reasons.push(reason), done(false, undefined));

  // 1 challenge exists and is still ISSUED (TV-S001-D04)
  if (input.record === undefined) return stop('CHALLENGE_UNKNOWN');
  if (input.record.status !== 'ISSUED') return stop('CHALLENGE_CONSUMED');
  const challenge = input.record.challenge;
  // 2 not expired (TV-S001-D03)
  const expiresAt = Date.parse(challenge.expiresAt);
  if (Number.isNaN(expiresAt) || input.now.getTime() > expiresAt) return stop('CHALLENGE_EXPIRED');
  // 3 bound to the requested DID (TV-S001-D05)
  if (
    challenge.subject !== input.requestedSubject ||
    input.didDocument.id !== input.requestedSubject
  ) {
    return stop('CHALLENGE_SUBJECT_MISMATCH');
  }
  // 4 operation and trust domain
  if (challenge.operation !== ADMIT_TRUST_ANCHOR || challenge.trustDomain !== input.trustDomain) {
    return stop('CHALLENGE_CONTEXT_MISMATCH');
  }
  // 5 the proof's verification method is in the resolved DID Document
  const vm = findVerificationMethod(input.didDocument, input.proof.verificationMethod);
  if (vm === undefined) return stop('VERIFICATION_METHOD_MISSING');

  // 6 purpose: listed under assertionMethod and bound as CREDENTIAL_ASSERTION (TV-S001-D06)
  let purposeValid = true;
  if (!authorizesAssertion(input.didDocument, vm.id)) {
    purposeValid = false;
    reasons.push('VERIFICATION_METHOD_NOT_FOR_ASSERTION');
  }
  if (
    input.keyReference === undefined ||
    input.keyReference.verificationMethod !== vm.id ||
    input.keyReference.purpose !== 'CREDENTIAL_ASSERTION' ||
    input.keyReference.status !== 'ACTIVE'
  ) {
    purposeValid = false;
    reasons.push('KEY_PURPOSE_NOT_CREDENTIAL_ASSERTION');
  }

  // 7 proof bound to this challenge, trust domain, verification method and purpose
  let possessionValid = true;
  if (
    input.proof.verificationMethod !== challenge.verificationMethod ||
    input.proof.challenge !== challenge.nonce ||
    input.proof.domain !== challenge.trustDomain ||
    input.proof.proofPurpose !== 'assertionMethod'
  ) {
    possessionValid = false;
    reasons.push('PROOF_BINDING_MISMATCH');
  }
  // 8 Ed25519 verification of eddsa-jcs-2022 hashData over the challenge (TV-S001-D01 / D02)
  if (possessionValid) {
    let signatureValid: boolean;
    try {
      signatureValid = verifyProof(
        { ...challenge },
        input.proof,
        decodeEd25519Multikey(vm.publicKeyMultibase),
      );
    } catch {
      signatureValid = false;
    }
    if (!signatureValid) {
      possessionValid = false;
      reasons.push('SIGNATURE_INVALID');
    }
  }
  return done(possessionValid, purposeValid);
}

function fact(
  name: 'ASSERTION_KEY_POSSESSION_VALID' | 'ASSERTION_KEY_PURPOSE_VALID',
  value: boolean,
  ref: string,
): FactInput {
  return { name, value, provenance: { source: 'KEY_POSSESSION_VERIFIER', ref } };
}

function toRfc3339(date: Date): string {
  return date.toISOString().replace(/\.\d{3}Z$/, 'Z');
}
